In [1]:
import pandas as pd

pd.read_json(r'C:\Users\ASUS\AppData\Local\Temp\e45b1967-2283-475f-a93d-c6e744a431d8_archive (8).zip.1d8\train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [6]:
pd.read_json(r'C:\Users\ASUS\AppData\Local\Temp\5f4a0f93-7e6d-45b5-8c83-e8076253118c_archive (8).zip.18c\test.json')

         id                                        ingredients
0     18009  [baking powder, eggs, all-purpose flour, raisi...
1     28583  [sugar, egg yolks, corn starch, cream of tarta...
2     41580  [sausage links, fennel bulb, fronds, olive oil...
3     29752  [meat cuts, file powder, smoked sausage, okra,...
4     35687  [ground black pepper, salt, sausage casings, l...
...     ...                                                ...
9939  30246  [large egg yolks, fresh lemon juice, sugar, bo...
9940  36028  [hot sauce, butter, sweet potatoes, adobo sauc...
9941  22339  [black pepper, salt, parmigiano reggiano chees...
9942  42525  [cheddar cheese, cayenne, paprika, plum tomato...
9943   1443  [cold water, olive oil, lime wedges, garlic cl...

[9944 rows x 2 columns]

In [19]:
import mysql.connector

mysql.connector.connect(host='localhost',user='root',password='')

ProgrammingError: 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

In [20]:
pd.read_sql_query()

TypeError: read_sql_query() missing 2 required positional arguments: 'sql' and 'con'